#!/usr/bin/env python3
"""Rewrite SYNC-STATE.md from git, per SYNC-CONTRACT.md section 5.1.

    python3 tools/syncstate.py            # record origin/main
    python3 tools/syncstate.py HEAD       # record the current checkout

The contract asks for this file on every push. Written by hand it goes stale
immediately -- it did, on its own first use: it recorded a feature-branch
commit while main moved four commits ahead within the hour. The design side
cannot tell a stale sync-state from a current one, which makes a wrong file
worse than no file. So it is generated, and regenerating is one command.
"""
import subprocess
import sys
import datetime

BODY = """# Sync state

Generated by `tools/syncstate.py`, per `SYNC-CONTRACT.md` section 5.1. This is the one
thing the design side cannot get for itself -- it turns "what changed since" from an
inference into a fact.

```
commit: {sha}
branch: {branch}
pushed: {when}
```

{subject}

**Regenerate this rather than editing it**, and do it after the push lands on `main`:

```bash
python3 tools/syncstate.py && git add SYNC-STATE.md
```

**Why it is generated.** The first version was written by hand and was stale within the
hour -- it recorded a feature-branch commit while `main` moved four ahead. Nothing on the
design side can tell a stale sync-state from a current one, so a wrong file is worse than
no file. The contract's own section 2 rule applies to the contract's own artifact: if a
claim contains a number, it belongs in a checker or a generator, not in prose someone
remembers to update.

**Development runs on `updated-outline-(sep-11)` and reaches `main` by pull request**, so
a sha taken between a push and its merge is not on `main` at all. Run this after the merge
and the sha above is the merge commit -- which is what section 5.1's template wanted and
could not express, since it assumed a direct push.
"""


def git(*args):
    return subprocess.run(('git',) + args, capture_output=True, text=True,
                          check=True).stdout.strip()


def main(ref='origin/main'):
    sha = git('rev-parse', ref)
    subject = git('log', '-1', '--pretty=%s', sha)
    when = git('log', '-1', '--pretty=%cI', sha)
    # Name the branch the sha is actually on, not the one checked out.
    heads = git('branch', '-r', '--contains', sha)
    branch = 'main' if any(h.strip() == 'origin/main' for h in heads.split('\n')) \
        else git('rev-parse', '--abbrev-ref', 'HEAD')
    text = BODY.format(sha=sha, branch=branch, when=when,
                       subject='Head commit: *%s*' % subject)
    with open('SYNC-STATE.md', 'w', encoding='utf-8') as fh:
        fh.write(text)
    print('SYNC-STATE.md -> %s (%s)' % (sha[:12], branch))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'origin/main')
